create table people (id int8 generated by default as identity, age int4, name varchar(255), primary key (id));
create table people (id int8 generated by default as identity, age int4, name varchar(255), primary key (id));
create table people (id int8 generated by default as identity, age int4, name varchar(255), primary key (id));
create table people (id int8 generated by default as identity, age int4, name varchar(255), primary key (id));
create table people (id int8 generated by default as identity, age int4, name varchar(255), primary key (id));
